server:
  port: 9090
logging:
  level:
    root: WARN
    com。netflix.eureka: false
    com。netflix.discovery: false
eureka:
  instance:
    hostname: localhost
  dashboard:
    path: /eureka/dashboard
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
zuul:
  add-proxy-headers: true