server:
    port: 9090
    
#spring:
#    jpa:
#        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
#        database: MYSQL
#        generate-ddl: true
#        hibernate:
#            ddl-auto: create-drop
#            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
#        properties:
#            hibernate.cache.use_second_level_cache: false
#            hibernate.cache.use_query_cache: false
#            hibernate.generate_statistics: false